name: crypto_position
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  elementary: ^3.2.1
  shared_preferences: ^2.5.5
  provider: ^6.1.5+1
  go_router: ^17.3.0
  flutter_secure_storage: ^9.2.4
  bybit:
    path: packages/bybit
  okx:
    path: packages/okx
  bitget:
    path: packages/bitget
  exchange:
    path: packages/exchange
  dio: ^5.8.0+1
  ui_kit:
    path: packages/ui_kit
  core:
    path: packages/core
  network:
    path: packages/network
  adaptive_layout: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
