name: network
description: Network infrastructure - RestClient over Dio and WebSocket layer
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.0
  core:
    path: ../core
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  stream_channel: ^2.1.2
