name: bybit_api
description: Bybit API client (REST + WebSocket)
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.3
  crypto: ^3.0.6
