name: network_shared
description: RestClient wrapper over Dio returning Result
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  core_shared:
    path: ../core_shared
  dio: ^5.8.0+1

dev_dependencies:
  test: ^1.25.0
